AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: searchphotos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::658514554862:role/service-role/search-photos-role-fdb1iia9'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: indexphotos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::658514554862:role/service-role/index-photos-role-ov4bjglk'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
  Bucket1:
    Type: 'AWS::S3::Bucket'
            
