AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::658514554862:role/service-role/search-photos-role-fdb1iia9'
      Runtime: python3.8
      Timeout: 3
